insert into ACTOR values( 1, 'Harrison Ford')
insert into ACTOR values( 2, 'William Shatner')
insert into ACTOR values( 3, 'Leonard Nimoy')
insert into ACTOR values( 4, 'Mark Hamill')
insert into ACTOR values( 5, 'Arnold Shwarzenegger')
insert into ACTOR values( 6, 'Tom Cruise')
insert into ACTOR values( 7, 'Robert Downey Jr.')
insert into ACTOR values( 8, 'Tim Allen')

insert into MOVIE values( 1, 'Raiders of the Lost Ark')
insert into MOVIE values( 2, 'Temple of Doom')
insert into MOVIE values( 3, 'Last Crusade')
insert into MOVIE values( 4, 'A New Hope')
insert into MOVIE values( 5, 'The Empire Strikes Back')
insert into MOVIE values( 6, 'Return of the Jedi')
insert into MOVIE values( 7, 'Blade Runner')
insert into MOVIE values( 8, 'Patriot Games')
insert into MOVIE values( 9, 'Enders Game')
insert into MOVIE values( 10, 'Air Force One')
insert into MOVIE values( 11, 'Star Trek: The Motion Picture')
insert into MOVIE values( 12, 'Star Trek: The Wrath of Khan')
insert into MOVIE values( 13, 'Star Trek: The Search for Spock')
insert into MOVIE values( 14, 'Star Trek: The Voyage Home')
insert into MOVIE values( 15, 'Star Trek: The Final Frontier')
insert into MOVIE values( 16, 'Star Trek: The Undiscovered Country')
insert into MOVIE values( 17, 'Terminator')
insert into MOVIE values( 18, 'Predator')
insert into MOVIE values( 19, 'The Expendables')
insert into MOVIE values( 20, 'The 6th Day')
insert into MOVIE values( 21, 'Raw Deal')
insert into MOVIE values( 22, 'Top Gun')
insert into MOVIE values( 23, 'Mission Impossible')
insert into MOVIE values( 24, 'The Mummy')
insert into MOVIE values( 25, 'Edge of Tomorrow')
insert into MOVIE values( 26, 'Dolittle')
insert into MOVIE values( 27, 'Avengers: Infinity War')
insert into MOVIE values( 28, 'Avengers: End Game')
insert into MOVIE values( 29, 'Iron Man')
insert into MOVIE values( 30, 'The Shaggy Dog')
insert into MOVIE values( 31, 'The Santa Clause')
insert into MOVIE values( 32, 'Toy Story')
insert into MOVIE values( 33, 'Zoom')
insert into MOVIE values( 34, 'Christmas with the Kranks')
insert into MOVIE values( 35, 'Galaxy Quest')

insert into CREDITS values (1,1)
insert into CREDITS values (1,2)
insert into CREDITS values (1,3)
insert into CREDITS values (1,4)
insert into CREDITS values (1,5)
insert into CREDITS values (1,6)
insert into CREDITS values (1,7)
insert into CREDITS values (1,8)
insert into CREDITS values (1,9)
insert into CREDITS values (1,10)
insert into CREDITS values (2,11)
insert into CREDITS values (2,12)
insert into CREDITS values (2,13)
insert into CREDITS values (2,14)
insert into CREDITS values (2,15)
insert into CREDITS values (2,16)
insert into CREDITS values (3,11)
insert into CREDITS values (3,12)
insert into CREDITS values (3,13)
insert into CREDITS values (3,14)
insert into CREDITS values (3,15)
insert into CREDITS values (3,16)
insert into CREDITS values (4,4)
insert into CREDITS values (4,5)
insert into CREDITS values (4,6)
insert into CREDITS values (5,17)
insert into CREDITS values (5,18)
insert into CREDITS values (5,19)
insert into CREDITS values (5,20)
insert into CREDITS values (5,21)
insert into CREDITS values (6,22)
insert into CREDITS values (6,23)
insert into CREDITS values (6,24)
insert into CREDITS values (6,25)
insert into CREDITS values (7,26)
insert into CREDITS values (7,27)
insert into CREDITS values (7,28)
insert into CREDITS values (7,29)
insert into CREDITS values (7,30)
insert into CREDITS values (8,30)
insert into CREDITS values (8,31)
insert into CREDITS values (8,32)
insert into CREDITS values (8,33)
insert into CREDITS values (8,34)
insert into CREDITS values (8,35)
